#ifndef GUARD_EVIPP_CONFIG_COMPILER_CLANG_HPP_INCLUDED
#define GUARD_EVIPP_CONFIG_COMPILER_CLANG_HPP_INCLUDED

#define EVIPP_COMPILER_CLANG
#define EVIPP_COMPILER_HAS_PRAGMA
#define EVIPP_PRAGMA(x) _Pragma(#x)


#endif //GUARD_CONFIG_COMPILER_CLANG_HPP_INCLUDED

