#ifndef GUARD_EVIPP_CONFIG_COMPILER_DETAIL_TEXT_HPP_INCLUDED
#define GUARD_EVIPP_CONFIG_COMPILER_DETAIL_TEXT_HPP_INCLUDED

#if defined(EVIPP_UNICODE_UTF16)
#	define EVIPP_TEXT(TXT) EVIPP_UTF16(TXT)
#elif defined(EVIPP_UNICODE_UTF32)
#	define EVIPP_TEXT(TXT) EVIPP_UTF32(TXT)
#elif defined(EVIPP_UNICODE_WCHART)
#	define EVIPP_TEXT(TXT) L##TXT
#else
#	define EVIPP_TEXT(TXT) TXT
#endif

#define EVIPP_UTF16(TXT) u##TXT
#define EVIPP_UTF32(TXT) U##TXT

#endif //GUARD_EVIPP_CONFIG_COMPILER_DETAIL_TEXT_HPP_INCLUDED

