#ifndef GUARD_EVIPP_CONFIG_COMPILER_MSVC_CHAR_TYPE_HPP_INCLUDED
#define GUARD_EVIPP_CONFIG_COMPILER_MSVC_CHAR_TYPE_HPP_INCLUDED

namespace evipp {
namespace config {
namespace compiler {
namespace msvc {


}}}}

#endif //GUARD_EVIPP_CONFIG_COMPILER_MSVC_CHAR_TYPE_HPP_INCLUDED

