#ifndef GUARD_EVIPP_CONFIG_COMPILER_GCC_TEXT_HPP_INCLUDED
#define GUARD_EVIPP_CONFIG_COMPILER_GCC_TEXT_HPP_INCLUDED

#include <evipp/config/compiler/detail/text.hpp>

#define EVIPP_UTF16(TXT) u##TXT
#define EVIPP_UTF32(TXT) U##TXT

#endif //GUARD_EVIPP_CONFIG_COMPILER_GCC_TEXT_HPP_INCLUDED

