#ifndef GUARD_PREPROCESSOR_TODO_HPP_INCLUDED
#define GUARD_PREPROCESSOR_TODO_HPP_INCLUDED

#include <evipp/preprocessor/todo.hpp>

#define EVIPP_TODO(x) EVIPP_MESSAGE("TODO: " x)

#endif //GUARD_PREPROCESSOR_TODO_HPP_INCLUDED

